version: "3"

services:
  backend:
    build:
      context: svelte-back/
      dockerfile: Dockerfile
    image: svelte-app-backend
    ports:
      - 5000:5000

  frontend:
    build:
      context: svelte-front/
      dockerfile: Dockerfile
    image: svelte-app-frontend
    ports:
    - 5173:80
    depends_on: ["backend"]